"""
reports.py -- generic, config-driven branded reporting.

Builds one accelerator report PDF for ANY project from the derived artifacts
(index.json, build_order_pipelines.csv, connections.csv) plus the engine catalog and
validation framework. Also exposes merge_pdfs() to stitch a set of PDFs into a single
omnibus with bookmarks (pypdf).
"""
from __future__ import annotations

import csv
import json
import os
from collections import Counter

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Spacer, PageBreak

from .branding import Brand
from . import engines as E
from . import validation as V


def _wave(v):
    try:
        return int(v)
    except (TypeError, ValueError):
        return 99


def _load_index(cfg):
    p = cfg.p(cfg.specs_dir, "index.json")
    return json.load(open(p)) if os.path.exists(p) else []


def build_report(cfg) -> str:
    B = Brand(cfg.branding)
    from .branding import Diagram  # local import to avoid cycle at module load
    idx = _load_index(cfg)
    kinds = Counter(r["kind"] for r in idx)
    engines = Counter(r["engine"] for r in idx)
    waves = Counter(_wave(r["wave"]) for r in idx)
    parity = sum(int(r.get("n_parity", 0)) for r in idx)

    conns = []
    cpath = cfg.out("connections.csv")
    if os.path.exists(cpath):
        conns = list(csv.DictReader(open(cpath)))
    used = [c for c in conns if int(c.get("n_pipelines", 0) or 0) > 0]

    W = letter[0] - 1.4 * inch

    def band(c, w, h):
        c.setFillColor(B.DARK)
        c.roundRect(0, 0, w, h, 6, fill=1, stroke=0)
        c.setFillColor(B.ACCENT)
        c.rect(0, 0, 5, h, fill=1, stroke=0)
        c.setFillColor(colors.white)
        c.setFont("Helvetica-Bold", 17)
        c.drawString(16, h - 28, f"MAYA - {cfg.project_name} Migration Report")
        c.setFillColor(colors.HexColor("#C8D2DE"))
        c.setFont("Helvetica", 9)
        c.drawString(16, h - 44, "Deterministic discovery, waves, engines, and "
                     "two-phase MAYA parity - generated by the accelerator")
        c.setFillColor(B.ACCENT)
        c.setFont("Helvetica-Bold", 11)
        c.drawString(16, 12, B.org)
        B.draw_dbx_lockup(c, w - 120, 9, mark=13, fs=12, color=colors.white)

    story = [Diagram(W, 60, band), Spacer(1, 10)]

    story.append(B.P("1. Overview", B.H1))
    story.append(B.P(f"Project <b>{cfg.project_name}</b> resolves to "
                     f"<b>{len(idx)}</b> pipelines with <b>{parity:,}</b> parity "
                     f"targets across <b>{len(waves)}</b> build waves. The estate is "
                     f"rebuilt on the medallion architecture with reusable engines and "
                     f"certified table-by-table under the MAYA two-phase technique "
                     f"(cheap logic proof on sampled dev, then full-scale parity on "
                     f"prod-copied data in SIT).", B.BODY))
    ov = [["Pipelines", str(len(idx))],
          ["Parity targets", f"{parity:,}"],
          ["Build waves", str(len(waves))],
          ["Connections in use", str(len(used))]]
    story.append(B.kv_table(ov, [2.6 * inch, 2.0 * inch],
                            header=["Metric", "Value"], fs=8))

    if kinds:
        story.append(B.P("Pipelines by kind", B.H3))
        story.append(B.kv_table([[k, str(kinds[k])] for k in sorted(kinds)],
                                [2.6 * inch, 1.6 * inch],
                                header=["Kind", "#"], fs=8))

    story.append(B.P("2. Reusable engine catalog", B.H1))
    erows = [[e["engine"], e["label"], str(engines.get(e["engine"], 0))]
             for e in E.catalog()]
    story.append(B.kv_table(erows, [0.6 * inch, 4.5 * inch, 1.0 * inch],
                            header=["Engine", "Role", "#Pipes"], fs=7.6))

    story.append(B.P("3. Build order (waves)", B.H1))
    if waves:
        cum, wr = 0, []
        for w in sorted(waves):
            cum += waves[w]
            wr.append([f"Wave {w}", str(waves[w]), str(cum)])
        story.append(B.kv_table(wr, [1.6 * inch, 1.6 * inch, 1.8 * inch],
                                header=["Wave", "#Pipelines", "Cumulative"], fs=7.8))
    else:
        story.append(B.P("Run `order` then `context` to populate wave figures.", B.SMALL))

    story.append(PageBreak())
    story.append(B.P("4. Strict parity validation", B.H1))
    story.append(B.P("Every table is proven against the source at a pinned point-in-time "
                     "across ten checks; any mismatch triggers a code-level drift loop "
                     "that repeats until green. No partial credit.", B.BODY))
    story.append(B.kv_table([[c[0], c[1]] for c in V.CHECKS],
                            [1.7 * inch, 5.2 * inch],
                            header=["Check", "Definition"], fs=7.4))
    story.append(B.P("Drift reason-codes", B.H3))
    story.append(B.kv_table([[k, v[0], v[1]] for k, v in V.REASON_CODES.items()],
                            [1.4 * inch, 3.2 * inch, 2.3 * inch],
                            header=["Code", "Meaning", "Action"], fs=7.4))

    story.append(B.P("5. MAYA validation: two-phase cost savings + sustained soak",
                     B.H1))
    story.append(B.P("MAYA proves correctness on a small <b>illusion of production</b> "
                     "in dev before spending money on prod-scale validation. Logic is "
                     "proven cheaply on sampled dev tables (MAYA-Dev); parity is proven "
                     "once at scale on production-copied data in SIT (MAYA-SIT), which "
                     "earns a <b>provisional</b> certification. Because point-in-time "
                     "parity proves state - not the ongoing incremental logic - both "
                     "systems then run in parallel and MAYA re-proves parity at T+7 and "
                     "T+14 (MAYA-Soak). A pipeline is <b>finally</b> certified only when "
                     "all three phases are green with zero drift.", B.BODY))
    m = cfg.maya
    wins = " & ".join(f"T+{d}" for d in m.soak_windows_days) or "T+7 & T+14"
    story.append(B.kv_table([
        ["MAYA-Dev", "dev",
         f"every table sampled to ~{m.sample_rows:,} rows ({m.sampling})",
         "schema, keys, referential integrity, no-extra-output, idempotency, sample"],
        ["MAYA-SIT", "sit", "production-copied data (full volume)",
         "all 10 checks at scale, point-in-time (provisional cert)"],
        ["MAYA-Soak", "soak", f"live parallel runs at {wins}",
         "all 10 on cumulative + incremental delta; zero drift (final cert)"],
    ], [1.0 * inch, 0.5 * inch, 2.7 * inch, 2.7 * inch],
        header=["Phase", "Env", "Data", "Proves"], fs=7.2))
    story.append(B.P("Cost model", B.H3))
    story.append(B.P("Full-volume compute is incurred only in MAYA-SIT, and only after "
                     "the logic is already correct - eliminating the repeated "
                     "prod-scale re-runs that dominate validation spend. Dev iterations "
                     "(the many drift-loop passes) run on a few thousand rows.", B.BODY))
    story += B.bullets([
        f"Sampling: {m.sampling}, seed {m.seed}, default {m.sample_rows:,} "
        "rows/table (reference/dim tables copied whole for join integrity).",
        f"Dev catalog: {m.dev_catalog}  |  SIT catalog: {m.sit_catalog}.",
        "Provisional gate: no promotion without MAYA-Dev AND MAYA-SIT green.",
        f"Final gate: sustained parity green at every soak window ({wins}), zero drift.",
    ])

    story.append(PageBreak())
    story.append(B.P("6. BI layer migration (dashboards + AI/BI)", B.H1))
    story.append(B.P("MAYA also migrates the BI layer (Looker / Tableau / Power BI). "
                     "Agents connect over MCP/API, extract every dashboard's queries, "
                     "AI-convert them to Databricks SQL (repointed at certified gold), "
                     "and prove each converted query returns the <b>exact same result</b> "
                     "as the original. Proven dashboards are republished to the BI tool; "
                     "in parallel each is replicated natively as a Lakeview dashboard "
                     "with an attached <b>Genie space</b> - bringing AI/BI on the same "
                     "certified numbers.", B.BODY))
    story.append(B.P("Agent flow (per BI object)", B.H3))
    story += B.bullets([
        "B0 Extract - pull query + datasource + tables via MCP/API.",
        "B1 Convert - AI translates the query to Databricks SQL, repoints tables.",
        "B2 Query-result parity - schema, row count, set equality (EXCEPT both ways), "
        "checksum, and order; drift-loop on the query until green.",
        "B3 Republish - publish the dashboard back to the BI tool, now on Databricks.",
        "B4 Genie + Lakeview - replicate natively + attach a Genie space seeded by the "
        "dashboard's own queries.",
    ])
    story.append(B.P("A BI object is done only when its converted query is result-for-"
                     "result identical to the original (against certified gold), it is "
                     "republished, and its Genie + Lakeview replica exist. BI work "
                     "starts only after the gold tables it reads are MAYA-certified.",
                     B.BODY))

    story.append(B.P("7. Method", B.H1))
    story += B.bullets([
        "Collect all source artifacts (code, procs, schedules, configs).",
        "Parse into one normalized dependency graph (objects + edges).",
        "Topologically order tables and pipelines into waves.",
        "Emit a deterministic build contract (needs/logic/output) per pipeline.",
        "Rebuild with reusable engines (E1-E7), SQL-first.",
        "Autonomous agent pool builds + validates + certifies wave by wave.",
        "MAYA-Dev (sample) then MAYA-SIT (scale); live dashboard; 100% parity to advance.",
        "MAYA-Soak: run in parallel, re-prove parity at T+7/T+14 (zero drift) to finalize.",
    ])

    out = cfg.out(f"{cfg.project_name}_accelerator_report.pdf")
    doc = SimpleDocTemplate(out, pagesize=letter, topMargin=0.6 * inch,
                            bottomMargin=0.6 * inch, leftMargin=0.7 * inch,
                            rightMargin=0.7 * inch,
                            title=f"{cfg.project_name} Accelerator Report")
    doc.build([s for s in story if s is not None],
              onFirstPage=B.footer, onLaterPages=B.footer)
    return out


def merge_pdfs(out_path: str, pdfs) -> dict:
    """Concatenate (label, path) PDFs into one file with top-level bookmarks."""
    from pypdf import PdfReader, PdfWriter
    writer = PdfWriter()
    summary = []
    for label, path in pdfs:
        if not os.path.exists(path):
            summary.append((label, 0))
            continue
        start = len(writer.pages)
        rdr = PdfReader(path)
        for pg in rdr.pages:
            writer.add_page(pg)
        writer.add_outline_item(label, start)
        summary.append((label, len(rdr.pages)))
    with open(out_path, "wb") as f:
        writer.write(f)
    return {"pages": len(writer.pages), "parts": summary}
