"""Generate the Databricks App: FastAPI backend + API contract + rebuilt UI.

The legacy backend/API/UI are regenerated to run on **Databricks Apps**, reading from
**Lakebase** over Postgres and authenticating through the app's OAuth identity. The
generator is deterministic (offline-safe): it authors real, runnable source from the
app manifest so the swarm/certifier has concrete artifacts to build and parity-test.
"""
from __future__ import annotations

import json
import os
from typing import Any, Dict, List

from .model import App, safe_ident


def _backend_source(app: App) -> str:
    routes: List[str] = []
    for ep in app.endpoints:
        fn = "ep_" + safe_ident(f"{ep.method}_{ep.path}")
        table = safe_ident(ep.entity) if ep.entity else ""
        if table:
            query = f"SELECT * FROM {app.schema}.{table} LIMIT 500"
            body = (f'    rows = _query("{query}")\n'
                    f'    return {{"data": rows}}')
        else:
            body = '    return {"data": []}'
        routes.append(
            f'@app.{ep.method.lower()}("{ep.path}")\n'
            f'def {fn}():\n'
            f'    """{ep.method} {ep.path}"""\n'
            f'{body}\n')
    routes_src = "\n\n".join(routes) if routes else \
        '@app.get("/api/health")\ndef health():\n    return {"status": "ok"}\n'
    return f'''"""Databricks App backend for '{app.key}' ({app.name}).

Generated by MAYA. Serves the migrated app read-models from Databricks Lakebase
(Postgres) and hosts the rebuilt UI. Runs on Databricks Apps (see app.yaml).
"""
import os

from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles

app = FastAPI(title="{app.name}")

_UI_DIR = os.path.join(os.path.dirname(__file__), "..", "ui")


def _conn():
    import psycopg  # provided by the Databricks Apps runtime
    return psycopg.connect(
        host=os.environ["LAKEBASE_HOST"],
        dbname=os.environ.get("LAKEBASE_DB", "{app.schema}"),
        user=os.environ["LAKEBASE_USER"],
        password=os.environ["LAKEBASE_PASSWORD"],
        sslmode="require",
    )


def _query(sql: str):
    with _conn() as cx, cx.cursor() as cur:
        cur.execute(sql)
        cols = [c.name for c in cur.description]
        return [dict(zip(cols, r)) for r in cur.fetchall()]


{routes_src}

if os.path.isdir(_UI_DIR):
    app.mount("/", StaticFiles(directory=_UI_DIR, html=True), name="ui")
'''


def _app_yaml(app: App) -> str:
    return (
        "# Databricks Apps manifest (generated by MAYA)\n"
        "command:\n"
        "  - uvicorn\n"
        "  - backend.app:app\n"
        "  - --host\n"
        "  - 0.0.0.0\n"
        "  - --port\n"
        "  - \"8000\"\n"
        "env:\n"
        f"  - name: LAKEBASE_DB\n    value: {app.schema}\n"
    )


def _openapi(app: App) -> dict:
    paths: Dict[str, Any] = {}
    for ep in app.endpoints:
        paths.setdefault(ep.path, {})[ep.method.lower()] = {
            "summary": f"{ep.method} {ep.path}",
            "x-entity": ep.entity, "x-screen": ep.screen,
            "responses": {"200": {"description": "OK"}},
        }
    return {"openapi": "3.0.3",
            "info": {"title": app.name, "version": "1.0.0"},
            "paths": paths}


def _ui_index(app: App) -> str:
    cards = "\n".join(
        f'      <li><a href="{s.key}.html">{s.title or s.key}</a></li>'
        for s in app.screens)
    return (f"<!doctype html><html><head><meta charset='utf-8'>"
            f"<title>{app.name}</title></head><body>"
            f"<h1>{app.name}</h1><p>{app.description}</p><ul>\n{cards}\n</ul>"
            f"</body></html>\n")


def _ui_screen(app: App, screen) -> str:
    eps = [e for e in app.endpoints if e.screen == screen.key]
    ep_path = eps[0].path if eps else "/api/health"
    return (f"<!doctype html><html><head><meta charset='utf-8'>"
            f"<title>{screen.title or screen.key}</title></head><body>"
            f"<h1>{screen.title or screen.key}</h1>"
            f"<table id='grid' border='1'></table>"
            f"<script>fetch('{ep_path}').then(r=>r.json()).then(d=>{{"
            f"const rows=(d.data||[]);const t=document.getElementById('grid');"
            f"if(!rows.length)return;const h=Object.keys(rows[0]);"
            f"t.innerHTML='<tr>'+h.map(k=>'<th>'+k+'</th>').join('')+'</tr>'+"
            f"rows.map(r=>'<tr>'+h.map(k=>'<td>'+r[k]+'</td>').join('')+'</tr>').join('');"
            f"}});</script></body></html>\n")


def generate(app: App, out_dir: str) -> Dict[str, Any]:
    """Write the generated Databricks App (backend + api + ui) under out_dir/generated."""
    gen = os.path.join(out_dir, "generated")
    be_dir = os.path.join(gen, "backend")
    ui_dir = os.path.join(gen, "ui")
    api_dir = os.path.join(gen, "api")
    for d in (be_dir, ui_dir, api_dir):
        os.makedirs(d, exist_ok=True)

    files: List[str] = []
    with open(os.path.join(be_dir, "app.py"), "w") as f:
        f.write(_backend_source(app))
    files.append("generated/backend/app.py")
    with open(os.path.join(be_dir, "__init__.py"), "w") as f:
        f.write("")
    with open(os.path.join(be_dir, "requirements.txt"), "w") as f:
        f.write("fastapi\nuvicorn\npsycopg[binary]\n")
    files.append("generated/backend/requirements.txt")
    with open(os.path.join(gen, "app.yaml"), "w") as f:
        f.write(_app_yaml(app))
    files.append("generated/app.yaml")

    with open(os.path.join(api_dir, "openapi.json"), "w") as f:
        json.dump(_openapi(app), f, indent=2)
    files.append("generated/api/openapi.json")

    with open(os.path.join(ui_dir, "index.html"), "w") as f:
        f.write(_ui_index(app))
    files.append("generated/ui/index.html")
    for s in app.screens:
        with open(os.path.join(ui_dir, f"{s.key}.html"), "w") as f:
            f.write(_ui_screen(app, s))
        files.append(f"generated/ui/{s.key}.html")

    return {
        "files": files,
        "api": {"built": True, "endpoints": len(app.endpoints)},
        "backend": {"built": True, "routes": len(app.endpoints)},
        "ui": {"built": True, "screens": len(app.screens)},
    }
